const DEFAULT_SESSION_TTL_DAYS = 14;
const DEFAULT_EMAIL_VERIFICATION_TTL_MINUTES = 10;
const DEFAULT_EMAIL_VERIFICATION_MAX_ATTEMPTS = 5;
const DEFAULT_EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS = 60;
const DEFAULT_EMAIL_VERIFICATION_MAX_SENDS_PER_WINDOW = 5;
const DEFAULT_EMAIL_VERIFICATION_RATE_WINDOW_MINUTES = 60;

export const SESSION_COOKIE_NAME =
  process.env.SESSION_COOKIE_NAME ?? 'postpilot_session';

export const SESSION_TTL_DAYS = Number(
  process.env.SESSION_TTL_DAYS ?? DEFAULT_SESSION_TTL_DAYS,
);

export const EMAIL_VERIFICATION_TTL_MINUTES = Number(
  process.env.EMAIL_VERIFICATION_TTL_MINUTES ??
    DEFAULT_EMAIL_VERIFICATION_TTL_MINUTES,
);

export const EMAIL_VERIFICATION_MAX_ATTEMPTS = Number(
  process.env.EMAIL_VERIFICATION_MAX_ATTEMPTS ??
    DEFAULT_EMAIL_VERIFICATION_MAX_ATTEMPTS,
);

export const EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS = Number(
  process.env.EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS ??
    DEFAULT_EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS,
);

export const EMAIL_VERIFICATION_MAX_SENDS_PER_WINDOW = Number(
  process.env.EMAIL_VERIFICATION_MAX_SENDS_PER_WINDOW ??
    DEFAULT_EMAIL_VERIFICATION_MAX_SENDS_PER_WINDOW,
);

export const EMAIL_VERIFICATION_RATE_WINDOW_MINUTES = Number(
  process.env.EMAIL_VERIFICATION_RATE_WINDOW_MINUTES ??
    DEFAULT_EMAIL_VERIFICATION_RATE_WINDOW_MINUTES,
);

export const EXPOSE_EMAIL_VERIFICATION_CODE =
  process.env.EXPOSE_EMAIL_VERIFICATION_CODE === 'true';

export const LOG_EMAIL_VERIFICATION_CODE =
  process.env.LOG_EMAIL_VERIFICATION_CODE !== 'false' &&
  process.env.NODE_ENV !== 'production';
